name: strgad
description: A helper library providing various functions to assist with string manipulation and formatting.
version: 0.1.0+1
repository: https://github.com/JHubi1/strgad

environment:
  sdk: ^3.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
