name: Testing
on:
  pull_request:
  workflow_dispatch:  

jobs:
  test:
    runs-on: ubuntu-latest
    name: Running tests
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.6.0
      - name: Install dependencies
        run: dart pub get
      - name: Static analysis
        run: dart analyze
      - name: VM Kernel
        run: dart test -p vm -c kernel
      - name: VM Source
        run: dart test -p vm -c source
      - name: VM Executable
        run: dart test -p vm -c exe
      - name: Chrome JS
        run: dart test -p chrome -c dart2js
      - name: Chrome WASM
        run: dart test -p chrome -c dart2wasm
